Repository AdobeDocs/cc-libraries-api, pull requests merged in 2020-11, with the labels that each got.

#27 Ash/sprint 1
  README.md
  src/pages/go-live/marketing/index.md
  src/pages/integrate/guides/configuring-events-webhooks/index.md
  src/pages/integrate/guides/getting-data/index.md
  src/pages/integrate/tutorials/quick-start-curl/index.md
  src/pages/integrate/tutorials/quick-start-nodejs/index.md
Labels: deploy, deploy:dev

#31 Update dependencies
  .env.example
  README.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: deploy

#30 Update index.md
  src/pages/integrate/guides/configuring-events-webhooks/index.md
Labels: deploy, deploy:dev

#43 Adding updated scopes.
  src/pages/go-live/review-process/index.md
  src/pages/integrate/guides/configuring-events-webhooks/index.md
  src/pages/integrate/setup/oauth/index.md
Labels: deploy:dev

#44 Prod commit
  src/pages/integrate/setup/oauth/index.md
Labels: deploy, deploy:dev
