Repository AdobeDocs/cc-libraries-api, pull requests merged in 2020-10, with the labels that each got.

#3 Stage test
  package-lock.json
  package.json
Labels: deploy:dev

#4 Update config and dep
  gatsby-config.js
  package-lock.json
  package.json
  yarn.lock
Labels: deploy, deploy:dev

#5 Update lock file
  .github/dependabot.yml
  gatsby-config.js
  package-lock.json
  package.json
Labels: deploy, deploy:dev

#7 Go live
  gatsby-config.js
  src/pages/go-live/index.md
  src/pages/go-live/review-process/index.md
Labels: deploy, deploy:dev

#8 Some brand changes (removing CC Libraries) and other cleanup for elem…
  src/pages/api/index.md
  src/pages/index.md
  src/pages/integrate/guides/configuring-events-webhooks/index.md
  src/pages/integrate/guides/getting-data/index.md
  src/pages/integrate/guides/index.md
  src/pages/integrate/guides/working-with-elements/accessing-file-formats/index.md
  src/pages/integrate/guides/working-with-elements/creating-elements/index.md
  src/pages/integrate/guides/working-with-elements/index.md
  src/pages/integrate/guides/working-with-elements/supported-elements/index.md
Labels: deploy:dev

#9 Community
  gatsby-config.js
  src/pages/api/index.md
  src/pages/community/index.md
  src/pages/go-live/index.md
  src/pages/go-live/marketing/index.md
  src/pages/go-live/review-process/index.md
  src/pages/index.md
  src/pages/integrate/guides/getting-data/index.md
  src/pages/integrate/guides/index.md
  src/pages/integrate/guides/working-with-elements/creating-elements/index.md
  src/pages/integrate/guides/working-with-elements/index.md
  src/pages/integrate/guides/working-with-elements/supported-elements/index.md
  src/pages/integrate/index.md
  src/pages/integrate/setup/developer-credentials/index.md
  src/pages/integrate/setup/oauth/index.md
  src/pages/integrate/tutorials/quick-start-curl/index.md
  src/pages/integrate/tutorials/quick-start-nodejs/index.md
  src/pages/overview/index.md
  src/pages/overview/product-overview/index.md
  src/pages/overview/sample-libraries/index.md
Labels: deploy, deploy:dev

#10 Changed wording on selectors
  src/pages/integrate/guides/working-with-elements/accessing-file-formats/index.md
Labels: deploy:dev

#12 Added marketing content.
  src/pages/go-live/marketing/index.md
Labels: deploy, deploy:dev

#17 Fix GH 404 links
  package.json
  src/@adobe/gatsby-theme-parliament/components/Contributors/index.js
  src/@adobe/gatsby-theme-parliament/components/GitHubActions/index.js
Labels: deploy, deploy:dev

#21 Update dependency
  package-lock.json
  package.json
  src/@adobe/gatsby-theme-parliament/components/Contributors/index.js
  src/@adobe/gatsby-theme-parliament/components/GitHubActions/index.js
Labels: dependency, deploy, deploy:dev
